default:
  image: ruby:3.2

pages:
  tags:
    - jekyll
  script:
    - echo "=== FICHIERS DANS LE REPO ==="
    - dir
    - echo "=== CONTENU DU FICHIER GEMFILE ==="
    - type Gemfile
    - echo "=== LIGNE D'ERREUR CI-DESSOUS ==="
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main




