default:
  image: ruby:3.2

before_script:
  - gem install bundler
  - bundle install

pages:
  script:
    - bundle exec jekyll build -d public
  pages: true
  artifacts:
    paths:
      - public
  only:
    - main  # ou "master" selon ta branche
