default:
  image: ruby:3.2

pages:
  tags:
    - jekyll
pages:
  script:
    - echo "=== PATH actuel ==="
    - echo $PATH
    - echo "=== Ruby version ==="
    - ruby -v
    - echo "=== Bundler version ==="
    - bundler -v
    - echo "=== Contenu du Gemfile ==="
    - type Gemfile
    - echo "=== Fin affichage ==="
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main


